# Generated by Django 5.2 on 2025-04-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('Новое', 'Новое'), ('Б/У', 'Б/У')], default='new', max_length=5, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('Ожидает', 'Ожидает'), ('Принята', 'Принята'), ('Отклонена', 'Отклонена')], default='waiting', max_length=9, verbose_name='Статус'),
        ),
    ]
